title: "Okan Can<br>Taskirmaz"
logo: /assets/Okantaskirmaz.png
description: >
 <br> Okancan2002@live.nl <br> 
  <hr> 
  <a href='https://okantaskirmaz.github.io/'>Research Projects</a> <br><br> 
  <a href='https://okantaskirmaz.github.io/Resume'>Resume</a> <br><br> 
  <hr>
show_downloads: false
theme: jekyll-theme-minimal
