title: "Okan Can<br>Taskirmaz"
logo: /assets/Okantaskirmaz.png
description: >
 Okancan2002@Live.nl <br> 
  <hr> 
  <a href='https://okantaskirmaz.github.io/'>Research Projects</a> <br><br> 
  <a href='https://okantaskirmaz.github.io/Resume.html'>Resume</a> <br><br> 
  <hr>
show_downloads: false
theme: jekyll-theme-minimal
