title: "Okan Can<br>Taskirmaz"
logo: /assets/img/jean_circ.png
description: >
 Okancan2002@Live.nl <br> 

  <hr> 
  <a href='https://urbanjeans.github.io/resume_portfolio/'>Research Projects</a> <br><br> 
  <a href='https://urbanjeans.github.io/resume_portfolio/RESUME.html'>Resume</a> <br><br> 
  <hr>
show_downloads: false
theme: jekyll-theme-minimal
